Reland "Typescriptify FormattedContentBuilder + move tests"
This reverts commit 51588addf9e2d0ffb91c85216729b2207fd500a8.

Reason for revert: Do not copy _test files in ts_library

Original change's description:
> Revert "Typescriptify FormattedContentBuilder + move tests"
>
> This reverts commit 4665866ae8dbf9652552e26595027cea85c518fd.
>
> Reason for revert: Speculative fix for build breakage which mentions
> typescript:
> Traceback (most recent call last):
>   File "../../third_party/devtools-frontend/src/third_party/typescript/ts_library.py", line 113, in <module>
>     sys.exit(main())
>   File "../../third_party/devtools-frontend/src/third_party/typescript/ts_library.py", line 90, in main
>     copy_all_typescript_sources(sources, path.dirname(tsconfig_output_location))
>   File "../../third_party/devtools-frontend/src/third_party/typescript/ts_library.py", line 109, in copy_all_typescript_sources
>     shutil.copy(generated_javascript_location, dest)
>   File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/shutil.py", line 139, in copy
>     copyfile(src, dst)
>   File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/shutil.py", line 97, in copyfile
>     with open(dst, 'wb') as fdst:
> IOError: [Errno 2] No such file or directory: '/b/s/w/ir/cache/builder/src/out/Debug/resources/inspector/formatter_worker/FormattedContentBuilder_test.js'
>
> Original change's description:
> > Typescriptify FormattedContentBuilder + move tests
> >
> > DISABLE_THIRD_PARTY_CHECK=needed typescript gni fix
> >
> > Bug: 1011811
> > Change-Id: I78f4b1286763ab45449b86fba0527e68ab9c258f
> > Reviewed-on: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2077664
> > Reviewed-by: Tim van der Lippe <tvanderlippe@chromium.org>
> > Commit-Queue: Jack Franklin <jacktfranklin@chromium.org>
>
> TBR=tvanderlippe@chromium.org,jacktfranklin@chromium.org
>
> Change-Id: I78cca47c227f4c152d0b90099f4a77c082129be8
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Bug: 1011811
> Reviewed-on: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2078916
> Commit-Queue: Mathias Bynens <mathias@chromium.org>
> Reviewed-by: Mathias Bynens <mathias@chromium.org>

DISABLE_THIRD_PARTY_CHECK=needed typescript gni fix

Change-Id: Id9d5e0b7f5ad55d23f7605319bca49cc7ca34a05
Bug: 1011811
Reviewed-on: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2078923
Reviewed-by: Jack Franklin <jacktfranklin@chromium.org>
Reviewed-by: Tim van der Lippe <tvanderlippe@chromium.org>
Commit-Queue: Tim van der Lippe <tvanderlippe@chromium.org>