Fix test setup errors in SourcesView_test
Before this CL, running unit tests would include this output:

```
==== PASS: SourcesView/viewForFile/records the correct media type in the DevTools.SourcesPanelFileOpened metric
ERROR: 'ScheduledRender: rendering devtools-sources-headers-view:'
[more stuff here]
```

This CL fixes that by ensuring a locale is created and also moves it to
use the describe helpers, rather than manually run all the setup.

Finally, running this test file in isolation would also fail because of
a missing PersistenceNetworkManager instance, so I added that too.

Bug: 1450893
Change-Id: I1ae6e7de66094994a3f04bf3dbdd262aa1d549fe
Reviewed-on: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4584593
Reviewed-by: Simon Zünd <szuend@chromium.org>
Auto-Submit: Jack Franklin <jacktfranklin@chromium.org>
Commit-Queue: Simon Zünd <szuend@chromium.org>