WebKit LayoutTests needs more resources.
It needs the PerformanceTests directory. This should fix the following
failures;
 * fast/harness/perftests/perf-runner-compute-statistics.html
 * fast/harness/perftests/runs-per-second-iterations.html
 * fast/harness/perftests/runs-per-second-log.html
 * fast/harness/perftests/measure-frame-time.html
 * fast/harness/perftests/measure-time.html
Which are failing with;
 CONSOLE ERROR: line 66: Uncaught ReferenceError: PerfTestRunner is not
 defined

It needs the extracted devtools resources (bug https://crbug.com/693723
created for this). This should fix the following failures;
 * inspector-protocol/heap-profiler/heap-samples-in-snapshot.html
 * inspector-protocol/heap-profiler/heap-snapshot-with-active-dom-object.html
 * inspector-protocol/heap-profiler/heap-snapshot-with-detached-dom-tree.html
 * inspector-protocol/heap-profiler/heap-snapshot-with-event-listener.html
Which are failing with;
 TypeError: HeapSnapshotWorker.HeapSnapshotLoader is not a constructor

BUG=52475,693723
NOTRY=true

Review-Url: https://codereview.chromium.org/2705653002
Cr-Original-Commit-Position: refs/heads/master@{#451412}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 2bf83ac0e39afbe323a7afe1bd89386ebda50034