Revert "Don't bypass CSP restrictions on eval from the console"
This reverts commit f6f9f51fd535c400e1358355e654afdf18ca7a0b.

Reason for revert: https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket.appspot.com/8876785684094997456/+/steps/E2E_tests/0/stdout

1) The Console Tab
       eval in console fails for pages with CSP that blocks eval:
     AssertionError: Didn't find expected CSP error message: expected '2' to include '\'unsafe-eval\' is not an allowed source of script'
      at Context.<anonymous> (out\Release\gen\test\e2e\console\console-eval-blocked-by-CSP_test.js:47:23)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:94:5)

Original change's description:
> Don't bypass CSP restrictions on eval from the console
> 
> Previously the console would allow evals even when the target page
> blocked evals via Content Security Policy. This made it hard to debug
> CSP-related issues on the page because users couldn't reproduce CSP
> eval errors in the console.
> 
> Use the new flag to Runtime.evaluate() that will cause CSP failures
> for eval from the console, if CSP on the page prevents unsafe eval.
> 
> Add a test.
> 
> Bug: chromium:1084558
> Change-Id: I916f36a2c02fbc1843de50851b72b54d2a3a7b8c
> Reviewed-on: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2253904
> Commit-Queue: Peter Marshall <petermarshall@chromium.org>
> Reviewed-by: Simon Zünd <szuend@chromium.org>

TBR=petermarshall@chromium.org,szuend@chromium.org

Change-Id: I59d3db7e9f0f1758c29e0edb67dce5ef92c4a735
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: chromium:1084558
Reviewed-on: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2256986
Reviewed-by: Tim van der Lippe <tvanderlippe@chromium.org>
Commit-Queue: Tim van der Lippe <tvanderlippe@chromium.org>