dom_extensions: do not use ? and initializer in function parameter
This is to fix a build error like below from swc

```
error: Parameter cannot have question mark and initializer

    |
460 | Node.prototype.traverseNextNode = function(stayWithin?: Node, skipShadowRoot?: boolean = false): Node|null {
    |                                                               ^^^^^^^^^^^^^^^^^^^^^^^^



Caused by:
    0: failed to process js file
    1: error was recoverable, but proceeding would result in wrong codegen
    2: Syntax Error
Failed to compile 1 file with swc.
```

Bug: chromium:1278663
Change-Id: I6f9b32bbebe883d691bdc414bc709d21c6c4cc95
Reviewed-on: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3329057
Auto-Submit: Takuto Ikuta <tikuta@chromium.org>
Reviewed-by: Tim Van der Lippe <tvanderlippe@chromium.org>
Commit-Queue: Takuto Ikuta <tikuta@chromium.org>